In [23]:
import numpy as np

[TOC]
# 一、ndarray类型
* 数组类型，使对于一组数据的运算更为简单，将一个数据作为一个对象，直接和其他数据计算即可，不用传统循环
* 作为多维数组,下标从0开始，定义时需要注意，是一个几维几列的数组，因此最外层用[]，里面是每行

In [84]:
a=np.array([[1,2,3,4],[11,22,33,44]])
print(a)

[[ 1  2  3  4]
 [11 22 33 44]]


In [85]:
a.shape

(2, 4)

In [86]:
a.size

8

In [87]:
a.dtype

dtype('int64')

# 二、创建
有三种方法创建ndarray：
* 由Python的列表、元组创建
* 用numpy中的函数创建，如：arange,ones,zeros
* 由字节流中创建
## 1.从python类型创建

In [30]:
a=[1,22,34,12,33]
x=np.array(a)
print(x)

[ 1 22 34 12 33]


In [29]:
x=np.array((4,5,6,7))
print(x)

[4 5 6 7]


In [31]:
x=np.array([[1,2],[9,3],[0.1,2.2]])
print(x)

[[1.  2. ]
 [9.  3. ]
 [0.1 2.2]]


## 2.从numpy函数创建
* np.arange(n) 类似Python的range，生成一个0..n-1的一维数组
* np.ones(shape) 依据shape形状生成全1数组
* np.zeros(shape) 全0
* np.full(shape,val) 全val值数组
* np.eye(n) 正方形n*n数组，对角线为1，其余0

In [88]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
x=np.zeros((2,3),dtype=np.int32)
print(x)

[[0 0 0]
 [0 0 0]]


In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
# 生成多维数组
x=np.ones((2,3,4))
print(x)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [39]:
print(x.shape)

(2, 3, 4)


* np.linespace() 根据起止数据等间距填充数据生成数组
* np.concatenate() 将两个或多个数组合并成一个新的数组

In [42]:
x=np.linspace(1,10,4)
# 1..10起止位置，4是生成4个元素,默认浮点数
print(x)

[ 1.  4.  7. 10.]


In [44]:
y=np.linspace(1,10,4,endpoint=False)
print(y)

[1.   3.25 5.5  7.75]


In [45]:
# 合并两个一维数组，元素合并，还是个一维数组
c=np.concatenate((x,y))
print(c)

[ 1.    4.    7.   10.    1.    3.25  5.5   7.75]


# 三.数组的维度变换
* .reshape(shape) 不改变数组元素，返回一个新的shape类型数组，原来数组不变（注意：改变前后两个数组总元素个数要一致，否则无法转换）
* .resize(shape) 与reshape功能一致，但修改原来数组
* .swapaxes(ax1,ax2) 将数组N个维度中的两个维度进行调换
* .flatten() 对数据进行降维，返回折叠后的一维数组，原来数组不变
* .astype(new_type) 将原数组类型转换为新类型，生成新的
* .tolist() 将ndarray数组转换成 ptyohn中的List 

In [52]:
x=np.ones((2,3,4),dtype=np.int32)
print(x)
print('-----2,3,4和3，8总个数不变 ，都是24-----------------')
y=x.reshape((3,8))
print(y)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
-----2,3,4和3，8总个数不变 ，都是24-----------------
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [53]:
# 将任何数据降到一维，原来数组不变
z=x.flatten()
print(z)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [54]:
y=x.astype(np.float)
print(y)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [55]:
x=np.full((2,3,4),11,dtype=np.int)
print(x)
print('---------多维数组转list-----------')
print(x.tolist())

[[[11 11 11 11]
  [11 11 11 11]
  [11 11 11 11]]

 [[11 11 11 11]
  [11 11 11 11]
  [11 11 11 11]]]
---------多维数组转list-----------
[[[11, 11, 11, 11], [11, 11, 11, 11], [11, 11, 11, 11]], [[11, 11, 11, 11], [11, 11, 11, 11], [11, 11, 11, 11]]]


# 四、数组的索引和切片
## 1.一维数组的索引和切片
* 索引通过[序号]
* 切片通过 [ : : ]两个：的方式设定起止，步长来切

In [56]:
x=np.array([9,8,7,6,5,4])

In [57]:
x[2]

7

In [58]:
x[1:5:2] #从下标1到5 ，步长2，切片出来也是一个ndarray数组

array([8, 6])

## 2.多维数组的索引和切片
* 索引通过 [ ， ，] 按维度序号
* 切片通过 [ : ，: ，：] ：用来起止   ，用来区分维度

In [59]:
x=np.arange(24).reshape((2,3,4))
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [61]:
x[1,2,3] #从三维数组，从层按需要索引出元素23来

23

In [62]:
x[:,1,-3]  # 第一个 : 表示不关心第一个维度，  第二个表示第二个维度取1  ， 第三个表时第三个维度取倒数第三个

array([ 5, 17])

In [65]:
x[:,1:3,:]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [67]:
x[:,:,::2] #仅第三个维度按步长2取值

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

# 五、运算
## 1.一元函数
* abs(x)  fabs(x) 计算数组各元素的绝对值
* sqrt(x) 平方根
* square(x) 平方
* log(x)  log10(x)  log2(x) 
* ceil(x) floor(x) 
* rint(x) 四舍五入
* modf(x) 将每个元素的整数、小数分别返回
* cos(x) sin tan
## 2.二元函数
* +-*/ ** 等
* < > == !=

In [71]:
x=np.arange(24).reshape((2,3,4))
y=np.square(x)
print(x)
print(y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[  0   1   4   9]
  [ 16  25  36  49]
  [ 64  81 100 121]]

 [[144 169 196 225]
  [256 289 324 361]
  [400 441 484 529]]]


In [72]:
# 求两个数组的最大值
np.maximum(x,y)

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]])

In [74]:
# 数组的比较
x > y

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]])

# 六、numpy数据的文件存取
## 1.csv文件
### （1）写入
```python
np.savetxt (frame,array,fmt='%.18e',delimiter=none)
```
* frame: 文件、字符串或产生器，也可以是gz,bz2压缩文件
* array:存入文件的数组
* fmt:写入文件的格式，如 %d %0.2f
* delimiter:分割字符串，默认为空格，csv要求为,

In [75]:
x=np.arange(100).reshape(5,20)
np.savetxt('x.csv',x,fmt='%.1f',delimiter=',')

In [76]:
# 读取csv文件，并显示
import pandas as pd
pd.read_csv("x.csv", encoding="GB2312")

0.0   1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0  \
0  20.0  21.0  22.0  23.0  24.0  25.0  26.0  27.0  28.0  29.0  30.0  31.0   
1  40.0  41.0  42.0  43.0  44.0  45.0  46.0  47.0  48.0  49.0  50.0  51.0   
2  60.0  61.0  62.0  63.0  64.0  65.0  66.0  67.0  68.0  69.0  70.0  71.0   
3  80.0  81.0  82.0  83.0  84.0  85.0  86.0  87.0  88.0  89.0  90.0  91.0   

   12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0  
0  32.0  33.0  34.0  35.0  36.0  37.0  38.0  39.0  
1  52.0  53.0  54.0  55.0  56.0  57.0  58.0  59.0  
2  72.0  73.0  74.0  75.0  76.0  77.0  78.0  79.0  
3  92.0  93.0  94.0  95.0  96.0  97.0  98.0  99.0

### (2)读取csv到数组
`np.loadtxt(frame,dtype=np.int,delimiter=',',unpack=False)`
* unpack：如是True，读入属性将分别写入不同变量

In [80]:
y=np.loadtxt('x.csv',dtype=np.int32,delimiter=',')
print(y)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


## 2.普通文件
`np.save(fname,array) 或者 np.savez`
* frmae:文件名，以.npy格式，压缩文件名.npz .numpy提供的文件格式
* array：数组
`np.load(fname)`
* fname；npy或npz都行
---
**这两个方法可以有效的做数据缓存，避免内存占用过大。且可以自己保存数组的维度信息，直接恢复即可，非常方便**


In [83]:
x=np.arange(100).reshape((2,5,10))
np.save('xx.npy',x)
y=np.load('xx.npy')
print(y)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


# 七、随机数及统计函数
## 1.随机数函数
使用 np.random.* 随机数函数
* rand(d0,d1...dn)  根据d0-dn随机生成数组，【0-1】的浮点数，随机分布
* randn(d0,d1..dn)  同上，正态分布
* randint(low,high,shpae) 范围【low,high】,生成sahpe形状的随机整数数组
* seed(s) : 随机数种子，s是给定的种子值

In [1]:
import numpy as np
s1=np.random.rand(3,4,5)
print(s1)

[[[0.05859738 0.40335639 0.29782203 0.91409685 0.13919125]
  [0.47766701 0.54341384 0.29147952 0.33042176 0.4800061 ]
  [0.3381066  0.22420062 0.32230819 0.96783153 0.91862354]
  [0.90242579 0.59483675 0.26319033 0.7722877  0.07570423]]

 [[0.73122047 0.45943199 0.65156122 0.54169592 0.08519098]
  [0.48383557 0.31936674 0.48238489 0.58306234 0.73581944]
  [0.67948575 0.2354313  0.61202152 0.38847745 0.89922679]
  [0.31484373 0.55600093 0.97815357 0.03433956 0.56716636]]

 [[0.15415114 0.63471301 0.65891465 0.44392103 0.04671603]
  [0.72893336 0.85989855 0.26096924 0.50542573 0.84240658]
  [0.02454416 0.96370102 0.22686249 0.60644684 0.31224993]
  [0.12585139 0.65033096 0.98761097 0.1525077  0.35592008]]]


In [2]:
s2=np.random.randn(3,4,5)
print(s2)

[[[ 0.08882737 -1.02226681  0.51019134  0.43953731 -3.32941883]
  [-1.96487036  1.79642241 -0.45235498  0.26374149  0.47574147]
  [ 1.74861955 -0.17440129  1.57688406  0.82091758 -2.03856522]
  [ 0.88971832 -0.82229959 -1.61650451  1.54030011 -0.75263179]]

 [[ 0.02601651  0.47227941  1.6799656  -0.62632139  0.45610358]
  [-0.22655077 -0.57955559  0.14201874 -0.98113409 -0.53766283]
  [-1.82075747 -1.01684113 -0.70962636  0.53995337  0.36468115]
  [-0.61565544  0.43525706 -0.36124159 -1.280589    1.28260228]]

 [[ 1.0660965  -1.78381034  0.61734157 -0.75617022 -0.54702947]
  [ 0.68820983 -1.63445934  0.2627312  -1.2442734   1.14761316]
  [-0.49733714 -1.02064574 -0.92315099  0.62272899  0.673504  ]
  [-0.71330232 -0.53765182  1.3545163  -0.67303164  1.45986423]]]


In [3]:
s3=np.random.randint(100,200,(3,4))
print(s3)

[[152 130 121 108]
 [101 103 143 121]
 [131 151 158 107]]


In [5]:
# 给定同一个随机数种子，可以再次生成相同的随机数数组，测试中很有用
np.random.seed(10)
s4=np.random.randint(100,200,(3,4))
print(s4)
np.random.seed(10)
s5=np.random.randint(100,200,(3,4))
print(s5)

[[109 115 164 128]
 [189 193 129 108]
 [173 100 140 136]]
[[109 115 164 128]
 [189 193 129 108]
 [173 100 140 136]]


In [ ]:
np.